name: Slither Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      id-token: write
      contents: write
      security-events: write
      statuses: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.github_token }}

      - name: Run Slither
        uses: crytic/slither-action@v0.2.0
        id: slither
        with:
          node-version: 16
          sarif: results.sarif
          fail-on: config

      - if: failure()
        uses: Ayrx/sarif_to_github_annotations@v0.2.2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}
