name: Tests

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  contents: write

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.github_token }}

      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Compile
        run: npx hardhat compile

      - name: Run unit tests
        run: npx hardhat node & npx hardhat test
